In [2]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Task-1: Scalar & Array Operations

In [ ]:
scalar = 3.7
arr = np.array([1, 2, 3, 4, 5,6])

sin_values = np.sin(arr)
cos_values = np.cos(arr)
tan_values = np.tan(arr)

print("sin:", sin_values)
print("cos:", cos_values)
print("tan:", tan_values)

sin: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
cos: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029]
tan: [ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619]


# Task-2: 3×2 Matrix Calculations

In [ ]:
# Creating a 3x2 matrix
matrix = np.array([[1, 2], [3, 4], [5, 6]])

# Trigonometric functions
sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)
asin_values = np.arcsin(np.clip(matrix / np.max(matrix), -1, 1))  # Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(matrix / np.max(matrix), -1, 1))
atan_values = np.arctan(matrix)

# Exponential and logarithm
exp_values = np.exp(matrix)
log_values = np.log(matrix)  # Natural logarithm (log base e)

# Absolute value and square root
abs_values = np.abs(matrix)
sqrt_values = np.sqrt(matrix)

# Remainder when divided by a scalar (2)
rem_values = np.remainder(matrix, 2)

# Rounding functions
round_values = np.round(matrix)
floor_values = np.floor(matrix)
ceil_values = np.ceil(matrix)

# Display results
print("Matrix:\n", matrix)
print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)
print("\nasine:\n", asin_values)
print("\nacosine:\n", acos_values)
print("\natangent:\n", atan_values)
print("\nexp:\n", exp_values)
print("\nlog (natural):\n", log_values)
print("\nabs:\n", abs_values)
print("\nsqrt:\n", sqrt_values)
print("\nrem (remainder when divided by 2):\n", rem_values)
print("\nround:\n", round_values)
print("\nfloor:\n", floor_values)
print("\nceil:\n", ceil_values)

Matrix:
 [[1 2]
 [3 4]
 [5 6]]

sin:
 [[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155 ]]

cos:
 [[ 0.54030231 -0.41614684]
 [-0.9899925  -0.65364362]
 [ 0.28366219  0.96017029]]

tan:
 [[ 1.55740772 -2.18503986]
 [-0.14254654  1.15782128]
 [-3.38051501 -0.29100619]]

asine:
 [[0.16744808 0.33983691]
 [0.52359878 0.72972766]
 [0.98511078 1.57079633]]

acosine:
 [[1.40334825 1.23095942]
 [1.04719755 0.84106867]
 [0.58568554 0.        ]]

atangent:
 [[0.78539816 1.10714872]
 [1.24904577 1.32581766]
 [1.37340077 1.40564765]]

exp:
 [[  2.71828183   7.3890561 ]
 [ 20.08553692  54.59815003]
 [148.4131591  403.42879349]]

log (natural):
 [[0.         0.69314718]
 [1.09861229 1.38629436]
 [1.60943791 1.79175947]]

abs:
 [[1 2]
 [3 4]
 [5 6]]

sqrt:
 [[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]]

rem (remainder when divided by 2):
 [[1 0]
 [1 0]
 [1 0]]

round:
 [[1 2]
 [3 4]
 [5 6]]

floor:
 [[1. 2.]
 [3. 4.]
 [5. 6.]]

ceil:
 [[1. 2

# Task-3: Vector Functions (2×3 Matrix)

In [4]:
# 2×3 matrix (float values)
vec = np.array([[3.2, 1.5, 4.8],
                [9.1, 2.6, 6.4]])

# Max value and index (clean index)
max_value = np.max(vec)
max_idx = np.unravel_index(np.argmax(vec), vec.shape)
max_index = (int(max_idx[0]), int(max_idx[1]))

# Min value and index (clean index)
min_value = np.min(vec)
min_idx = np.unravel_index(np.argmin(vec), vec.shape)
min_index = (int(min_idx[0]), int(min_idx[1]))


# Length of vector (total elements)
vec_length = vec.size

# Sorting
# Row-wise descending
rowwise_desc = np.sort(vec, axis=1)[:, ::-1]

# Entire matrix descending
full_desc = np.sort(vec.flatten())[::-1]

# Sum
sum_values = np.sum(vec)

# Product
prod_values = np.prod(vec)

# Median
median_value = np.median(vec)

# Mean
mean_value = np.mean(vec)

# Standard Deviation
std_dev = np.std(vec)

# Display results
print("Max value:", max_value, "at index", max_index)
print("Min value:", min_value, "at index", min_index)
print("Total number of elements:", vec_length)
print("Row-wise descending sort:\n", rowwise_desc)
print("Entire matrix descending sort:", full_desc)
print("Sum of elements:", sum_values)
print("Product of elements:", prod_values)
print("Median value:", median_value)
print("Mean value:", mean_value)
print("Standard deviation:", std_dev)


Max value: 9.1 at index (1, 0)
Min value: 1.5 at index (0, 1)
Total number of elements: 6
Row-wise descending sort:
 [[4.8 3.2 1.5]
 [9.1 6.4 2.6]]
Entire matrix descending sort: [9.1 6.4 4.8 3.2 2.6 1.5]
Sum of elements: 27.6
Product of elements: 3488.8089600000008
Median value: 4.0
Mean value: 4.6000000000000005
Standard deviation: 2.5527762664727724
